### ISSUE TITLE
Docker container exiting without error logging

### ISSUE THREAD

**Issue by Annelies-P** [Informatievlaanderen/VSDS-LDESWorkbench-Services#36]
Is this LDES Client supposed to work with any LDES?

It seems to be working with https://private-api.gipod.test-vlaanderen.be/api/v1/ldes/mobility-hindrances,
but trying with https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten makes the container exit without any logging.

Some debugging led me to replacing this requestmethod "HEAD" with "GET"  (got stuck with response HTTP 403 for favicon.ico using "HEAD")
https://github.com/Informatievlaanderen/VSDS-LDESClientCli/blob/4c11496b0575f4638260259a07629d176f413156/src/main/java/be/vlaanderen/informatievlaanderen/ldes/client/cli/services/EndpointChecker.java#L21

The FragmentProcessor seems to start but ends up crashing the container without error message.

Are there any constraints on the datasource?

**Comment by MPParsley** [comment]
The problem here is that the client isn't following redirects:

```% curl -i "https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten" | grep "Location"
Location: https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten?generatedAtTime=2022-11-15T00:02:43.251Z
```

**Comment by MPParsley** [comment]
HEAD is now supported, these are now working:

```
docker run -t ldes-cli "--url" "https://apidg.gent.be/opendata/adlib2eventstream/v1/industriemuseum/objecten"
docker run -t ldes-cli "--url" "https://apidg.gent.be/opendata/adlib2eventstream/v1/dmg/tentoonstellingen"
```
